### PR TITLE
Correct SignalHandlerProcessor to avoid error when pcntl is not loaded

### LINKED ISSUE #87: the SignalHandlerProcessor does not deal properly with cases where pcntl is not available
On windows, pcntl is not available at all. The SignalHandlerProcessor tries to deal with it, but it does it only in ``process``. Other functions are broken:

- ``sleep`` should become a noop when the ext is not loaded instead of triggering a fatal error
- ``setDefaultOptions`` should avoid using the constants to define the default value (it should define an empty array in this case, but the option itself should still be registered so that it is accepted)

### PR DESCRIPTION
**Pull request by odolbeau**
Fix #87 

Is it ok for you @stof?

### CODE REVIEW

File: src/Swarrot/Processor/SignalHandler/SignalHandlerProcessor.php [hunk 1]
```diff
@@ -41,6 +41,10 @@ public function __construct(ProcessorInterface $processor, LoggerInterface $logg
      */
     public function setDefaultOptions(OptionsResolverInterface $resolver)
     {
+        if (!extension_loaded('pcntl')) {
+            return;
```
Comment (stof) [inline src/Swarrot/Processor/SignalHandler/SignalHandlerProcessor.php]: this is not. The ``signal_handler_signals`` option should still be know by the OptionsResolver to prevent exceptions when using it because of an unknown option

File: src/Swarrot/Processor/SignalHandler/SignalHandlerProcessor.php [hunk 2]
```diff
@@ -51,6 +55,10 @@ public function setDefaultOptions(OptionsResolverInterface $resolver)
      */
     public function sleep(array $options)
     {
+        if (!extension_loaded('pcntl')) {
+            return false;
```
Comment (stof) [inline src/Swarrot/Processor/SignalHandler/SignalHandlerProcessor.php]: this should return ``true``. Otherwise, you always stop it when the queue is empty (which is the job of the InsomniacProcessor)

**Comment by stof** [comment]
Hurrah. HHVM broke their phar support...

**Comment by odolbeau** [comment]
@stof Is there something to do to avoid the error in hhvm tests? It's also broken on master.
Should I update the `.travis.yml` to accept failures with hhvm?

**Comment by stof** [comment]
@odolbeau I would do that for now yes, until they fix this
